export default {
    SIGNUP_ACTIONS: {
        RESET_ERROR: 'RESET_ERROR',
        SIGNUP_WITH_EMAIL: 'SIGNUP_WITH_EMAIL',
        RESET_PASSWORD_WITH_EMAIL: 'RESET_PASSWORD_WITH_EMAIL',
        CHECK_SIGNUP_DONE: 'CHECK_SIGNUP_DONE',
        SET_SIGNUP_DATA: 'SET_SIGNUP_DATA'
    }
}
